name: DeepSeek In Github Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-ollama-serve:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ollama

    - name: Run Ollama Serve in the background
      run: |
        nohup ollama serve > ollama.log 2>&1 &
        echo $! > ollama.pid
        sleep 5  # Give it some time to start

    - name: Check if Ollama Serve is running
      run: |
        if ps -p $(cat ollama.pid) > /dev/null; then
          echo "Ollama Serve is running with PID $(cat ollama.pid)"
        else
          echo "Ollama Serve failed to start"
          exit 1
        fi

    - name: Download deepseek-coder:1.3b model
      run: |
        ollama run deepseek-coder:1.3b
